// Theme toggle
const toggleBtn = document.getElementById('theme-toggle');
const body = document.body;

toggleBtn.addEventListener('click', () => {
  body.classList.toggle('dark');
  toggleBtn.textContent = body.classList.contains('dark') ? '☀️' : '🌙';
});

// Smooth scroll
document.querySelectorAll('nav a').forEach(link => {
  link.addEventListener('click', e => {
    e.preventDefault();
    const target = document.querySelector(link.getAttribute('href'));
    target.scrollIntoView({ behavior: 'smooth' });
  });
});

// Project Data
const projects = [
  {
    title: "RAG | LLM",
    description: "This project implements a Retrieval-Augmented Generation (RAG) chatbot using a multi-agent architecture powered by the Model Context Protocol (MCP). It allows users to upload documents and ask questions — with answers generated by an LLM using relevant document context retrieved via vector embeddings.",
    date: "August 2025",
    image: "images/agnt.png",
    github: "https://github.com/Nvkl-17/RAG-with-MCP"
  },
  {
    title: "PySpark | Analysis",
    description: "The Cricket Analysis using PySpark with Streamlit project successfully demonstrates the application of big data technologies and interactive web development to analyze and visualize cricket match data. By leveraging the power of PySpark, the project handles large datasets efficiently, enabling insightful data processing and analysis, including player performance metrics, match outcomes, and team comparisons.",
    date: " Dec 24",
    image: "images/pyspark.png",
    github: "https://github.com/Nvkl-17/Pyspark-Cricket-Data-Analysis-"
  },
  {
    title: " IOT | Speech to Text ",
    description: "This project aims to implement a text-to-speech (TTS) system using an ESP32 microcontrollertointeract with Google’s Gen-AI Gemini model. The ESP32 is connected to a speaker viaanaudioamplifier, allowing it to convert text-based responses generated by the Gemini AI intospeech. Thesystem utilizes the ESP32’s Wi-Fi capabilities to query the Gen-AI Gemini API for AI-generatedanswers to user-provided questions.",
    date: " Dec 2024",
    image: "images/iot.png",
    github: "https://github.com/Nvkl-17/Esp32-geminichatbot"
  },
  {
    title: " ML | Neural Network  ",
    description: "Self Driving Car by using a combination of a feedforward neural network for path prediction, collision detection through (polysIntersect), and training with 1,000 mutated versions of the network, helps to efficiently learn the safest paths for self-driving cars",
    date: " Jan 2024",
    image: "2.png",
    github: "https://github.com/Nvkl-17/PathFindingusingML"
  }
];
// Certification Data
const certs = [
  {
    title: "Oracle Cloud Infrastructure with AI ",
    description: "Completed Oracle Academy certification in Java programming.",
    image: "orc.jpeg"
  },
  {
    title: "NPTEL – Big Data Computing",
    description: "Certified course in Big Data fundamentals with Elite performer badge.",
    image: "Big Data.png"
  },
  {
    title: "Infosys - NoSql Databases",
    description: "Completed NoSql Essentials course covering Neo4j and mongoDB Engineering.",
    image: "NoSql.png"
  },
   {
    title: "NPTEL – Java Programming",
    description: "Certified course in Java fundamentals with top performer badge.",
    image: "Programming in Java.jpg"
  },
   {
    title: "Infosys - DSA in Java ",
    description: "Completed DSA Essentials course in java covers with problem solving.",
    image: "DSA.png"
  },

   {
    title: "NPTEL – Python Programming",
    description: "Certified course in python fundamentals with top performer badge.",
    image: "python.jpg"
  },
];

// Load Projects
const projectsContainer = document.getElementById('projects-container');
projects.forEach(proj => {
  const card = document.createElement('div');
  card.classList.add('card');
  card.innerHTML = `
    <img src="${proj.image}" alt="${proj.title}">
    <h3>${proj.title}</h3>
    <p>${proj.description}</p>
    <p class="date">Date: ${proj.date}</p>
    <a href="${proj.github}" target="_blank" class="github-link">🔗 GitHub</a>
  `;
  projectsContainer.appendChild(card);
});

// Load Certifications
const certContainer = document.getElementById('cert-container');
certs.forEach(cert => {
  const card = document.createElement('div');
  card.classList.add('cert-card');
  card.innerHTML = `
    <img src="${cert.image}" alt="${cert.title}">
    <h4>${cert.title}</h4>
    <p>${cert.description}</p>
  `;
  certContainer.appendChild(card);
});

// Project data
